<?php

return [

    'columns' => [
        'score',
        'score_p1',
        'score_p2',
        'score_p3',
        'score_p4',
        'score_p5',
        'score_p6',
        'score_p7',
        'score_p8',
        'score_p9',
        'score_p10',
        'assists',
        'steals',
        'blocks',
        'turnovers',
        'fouls',
        'personal_fouls',
        'technical_fouls',
        'flagrant_fouls',
        'three_points',
        'three_points_made',
        'two_points',
        'two_points_made',
        'field_goals',
        'field_goals_made',
        'free_throws',
        'free_throws_made',
        'rebounds',
        'offensive_rebounds',
        'defensive_rebounds',
        'timeouts',
        'efficiency',
    ],

];
