<?php

return [

    'columns' => [
        ['id' => 'score',              'label' => 'Score',              'type' => 'integer'],
        ['id' => 'score_p1',           'label' => 'Score P1',           'type' => 'integer'],
        ['id' => 'score_p2',           'label' => 'Score P2',           'type' => 'integer'],
        ['id' => 'score_p3',           'label' => 'Score P3',           'type' => 'integer'],
        ['id' => 'score_p4',           'label' => 'Score P4',           'type' => 'integer'],
        ['id' => 'score_p5',           'label' => 'Score P5',           'type' => 'integer'],
        ['id' => 'score_p6',           'label' => 'Score P6',           'type' => 'integer'],
        ['id' => 'score_p7',           'label' => 'Score P7',           'type' => 'integer'],
        ['id' => 'score_p8',           'label' => 'Score P8',           'type' => 'integer'],
        ['id' => 'score_p9',           'label' => 'Score P9',           'type' => 'integer'],
        ['id' => 'score_p10',          'label' => 'Score P10',          'type' => 'integer'],
        ['id' => 'assists',            'label' => 'Assists',            'type' => 'integer'],
        ['id' => 'steals',             'label' => 'Steals',             'type' => 'integer'],
        ['id' => 'blocks',             'label' => 'Blocks',             'type' => 'integer'],
        ['id' => 'turnovers',          'label' => 'Turnovers',          'type' => 'integer'],
        ['id' => 'fouls',              'label' => 'Fouls',              'type' => 'integer'],
        ['id' => 'personal_fouls',     'label' => 'Personal Fouls',     'type' => 'integer'],
        ['id' => 'technical_fouls',    'label' => 'Technical Fouls',    'type' => 'integer'],
        ['id' => 'flagrant_fouls',     'label' => 'Flagrant Fouls',     'type' => 'integer'],
        ['id' => 'three_points',       'label' => '3PT',                'type' => 'integer'],
        ['id' => 'three_points_made',  'label' => '3PT Made',           'type' => 'integer'],
        ['id' => 'two_points',         'label' => '2PT',                'type' => 'integer'],
        ['id' => 'two_points_made',    'label' => '2PT Made',           'type' => 'integer'],
        ['id' => 'field_goals',        'label' => 'FG',                 'type' => 'integer'],
        ['id' => 'field_goals_made',   'label' => 'FG Made',            'type' => 'integer'],
        ['id' => 'free_throws',        'label' => 'FT',                 'type' => 'integer'],
        ['id' => 'free_throws_made',   'label' => 'FT Made',            'type' => 'integer'],
        ['id' => 'rebounds',           'label' => 'Rebounds',           'type' => 'integer'],
        ['id' => 'offensive_rebounds', 'label' => 'Offensive Rebounds', 'type' => 'integer'],
        ['id' => 'defensive_rebounds', 'label' => 'Defensive Rebounds', 'type' => 'integer'],
        ['id' => 'timeouts',           'label' => 'Timeouts',           'type' => 'integer'],
    ],

    'calculated_columns' => [
        ['id' => 'score_avg',              'label' => 'Score AVG',              'type' => 'float', 'method' => 'avg'],
        ['id' => 'assists_avg',            'label' => 'Assists AVG',            'type' => 'float', 'method' => 'avg'],
        ['id' => 'steals_avg',             'label' => 'Steals AVG',             'type' => 'float', 'method' => 'avg'],
        ['id' => 'blocks_avg',             'label' => 'Blocks AVG',             'type' => 'float', 'method' => 'avg'],
        ['id' => 'three_points_avg',       'label' => '3PT AVG',                'type' => 'float', 'method' => 'avg'],
        ['id' => 'three_points_percent',   'label' => '3PT %',                  'type' => 'float', 'method' => 'percent'],
        ['id' => 'three_points_made_avg',  'label' => '3PT Made AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'two_points_avg',         'label' => '2PT AVG',                'type' => 'float', 'method' => 'avg'],
        ['id' => 'two_points_percent',     'label' => '2PT %',                  'type' => 'float', 'method' => 'percent'],
        ['id' => 'two_points_made_avg',    'label' => '2PT Made AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'field_goals_percent',    'label' => 'FG %',                   'type' => 'float', 'method' => 'percent'],
        ['id' => 'field_goals_avg',        'label' => 'FG AVG',                 'type' => 'float', 'method' => 'avg'],
        ['id' => 'field_goals_made_avg',   'label' => 'FG Made AVG',            'type' => 'float', 'method' => 'avg'],
        ['id' => 'free_throws_avg',        'label' => 'FT AVG',                 'type' => 'float', 'method' => 'avg'],
        ['id' => 'free_throws_percent',    'label' => 'FT %',                   'type' => 'float', 'method' => 'percent'],
        ['id' => 'free_throws_made_avg',   'label' => 'FT Made AVG',            'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p1_avg',           'label' => 'Score Q1 AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p2_avg',           'label' => 'Score Q2 AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p3_avg',           'label' => 'Score Q3 AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p4_avg',           'label' => 'Score Q4 AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p5_avg',           'label' => 'Score OT1 AVG',          'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p6_avg',           'label' => 'Score OT2 AVG',          'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p7_avg',           'label' => 'Score OT3 AVG',          'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p8_avg',           'label' => 'Score OT4 AVG',          'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p9_avg',           'label' => 'Score OT5 AVG',          'type' => 'float', 'method' => 'avg'],
        ['id' => 'score_p10_avg',          'label' => 'Score OT6 AVG',          'type' => 'float', 'method' => 'avg'],
        ['id' => 'turnovers_avg',          'label' => 'Turnover AVG',           'type' => 'float', 'method' => 'avg'],
        ['id' => 'fouls_avg',              'label' => 'Foul AVG',               'type' => 'float', 'method' => 'avg'],
        ['id' => 'personal_fouls_avg',     'label' => 'Personal Foul AVG',      'type' => 'float', 'method' => 'avg'],
        ['id' => 'technical_fouls_avg',    'label' => 'Technical Foul AVG',     'type' => 'float', 'method' => 'avg'],
        ['id' => 'flagrant_fouls_avg',     'label' => 'Flagrant Foul AVG',      'type' => 'float', 'method' => 'avg'],
        ['id' => 'rebounds_avg',           'label' => 'Rebound AVG',            'type' => 'float', 'method' => 'avg'],
        ['id' => 'offensive_rebounds_avg', 'label' => 'Offensive Rebound AVG',  'type' => 'float', 'method' => 'avg'],
        ['id' => 'defensive_rebounds_avg', 'label' => 'Defensive Rebound AVG',  'type' => 'float', 'method' => 'avg'],
        ['id' => 'efficiency',             'label' => 'Efficiency',             'type' => 'float', 'method' => 'efficiency'],
    ],

];
